part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LANDING_PAGE = _Paths.LANDING_PAGE;
  static const HALAMAN_LOGIN = _Paths.HALAMAN_LOGIN;
  static const LOGIN_EMAIL = _Paths.LOGIN_EMAIL;
  static const LUPA_PASSWORD = _Paths.LUPA_PASSWORD;
  static const VERIFIKASI_EMAIL = _Paths.VERIFIKASI_EMAIL;
  static const UBAH_PASSWORD = _Paths.UBAH_PASSWORD;
  static const PROFIL = _Paths.PROFIL;
  static const EDIT_PROFIL = _Paths.EDIT_PROFIL;
  static const GANTI_PASSWORD = _Paths.GANTI_PASSWORD;
  static const PILIH_BAHASA = _Paths.PILIH_BAHASA;
  static const ALAMAT_SAYA = _Paths.ALAMAT_SAYA;
  static const CUTI = _Paths.CUTI;
  static const LIST_CUTI = _Paths.LIST_CUTI;
  static const DETAIL_CUTI = _Paths.DETAIL_CUTI;
  static const REIMBURSEMENT = _Paths.REIMBURSEMENT;
  static const REIMBURSEMENT_FORM = _Paths.REIMBURSEMENT_FORM;
  static const REIMBURSEMENT_TYPE = _Paths.REIMBURSEMENT_TYPE;
  static const REIMBURSEMENT_DETAIL_INPUT = _Paths.REIMBURSEMENT_DETAIL_INPUT;
  static const REIMBURSEMENT_DETAIL = _Paths.REIMBURSEMENT_DETAIL;
  static const SURAT_TUGAS = _Paths.SURAT_TUGAS;
  static const SURAT_TUGAS_FORM = _Paths.SURAT_TUGAS_FORM;
  static const SURAT_TUGAS_DETAIL = _Paths.SURAT_TUGAS_DETAIL;
  static const HRD_CUTI = _Paths.HRD_CUTI;
  static const HRD_DETAIL_CUTI = _Paths.HRD_DETAIL_CUTI;
  static const KARYAWAN_ABSEN = _Paths.KARYAWAN_ABSEN;
  static const KARYAWAN_ABSEN_WFO_WFH = _Paths.KARYAWAN_ABSEN_WFO_WFH;
  static const LEMBUR = _Paths.LEMBUR;
  static const FORM_LEMBUR = _Paths.FORM_LEMBUR;
  static const DETAIL_LEMBUR = _Paths.DETAIL_LEMBUR;
  static const KARYAWAN_ABSEN_WFA = _Paths.KARYAWAN_ABSEN_WFA;
  static const RIWAYAT_ABSEN = _Paths.RIWAYAT_ABSEN;
  static const HRD_LEMBUR = _Paths.HRD_LEMBUR;
  static const HRD_DETAIL_LEMBUR = _Paths.HRD_DETAIL_LEMBUR;
  static const HRD_SURAT_TUGAS = _Paths.HRD_SURAT_TUGAS;
  static const HRD_DETAIL_SURAT_TUGAS = _Paths.HRD_DETAIL_SURAT_TUGAS;
  static const ABSENSI = _Paths.ABSENSI;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LANDING_PAGE = '/landing-page';
  static const HALAMAN_LOGIN = '/halaman-login';
  static const LOGIN_EMAIL = '/login-email';
  static const LUPA_PASSWORD = '/lupa-password';
  static const VERIFIKASI_EMAIL = '/verifikasi-email';
  static const UBAH_PASSWORD = '/ubah-password';
  static const PROFIL = '/profil';
  static const EDIT_PROFIL = '/edit-profil';
  static const GANTI_PASSWORD = '/ganti-password';
  static const PILIH_BAHASA = '/pilih-bahasa';
  static const ALAMAT_SAYA = '/alamat-saya';
  static const CUTI = '/cuti';
  static const LIST_CUTI = '/list-cuti';
  static const DETAIL_CUTI = '/detail-cuti';
  static const REIMBURSEMENT = '/reimbursement';
  static const REIMBURSEMENT_FORM = '/reimbursement-form';
  static const REIMBURSEMENT_TYPE = '/reimbursement-type';
  static const REIMBURSEMENT_DETAIL_INPUT = '/reimbursement-detail-input';
  static const REIMBURSEMENT_DETAIL = '/reimbursement-detail';
  static const SURAT_TUGAS = '/surat-tugas';
  static const SURAT_TUGAS_FORM = '/surat-tugas-form';
  static const SURAT_TUGAS_DETAIL = '/surat-tugas-detail';
  static const HRD_CUTI = '/hrd-cuti';
  static const HRD_DETAIL_CUTI = '/hrd-detail-cuti';
  static const KARYAWAN_ABSEN = '/karyawan-absen';
  static const KARYAWAN_ABSEN_WFO_WFH = '/karyawan-absen-wfo-wfh';
  static const LEMBUR = '/lembur';
  static const FORM_LEMBUR = '/form-lembur';
  static const DETAIL_LEMBUR = '/detail-lembur';
  static const KARYAWAN_ABSEN_WFA = '/karyawan-absen-wfa';
  static const RIWAYAT_ABSEN = '/riwayat-absen';
  static const HRD_LEMBUR = '/hrd-lembur';
  static const HRD_DETAIL_LEMBUR = '/hrd-detail-lembur';
  static const HRD_SURAT_TUGAS = '/hrd-surat-tugas';
  static const HRD_DETAIL_SURAT_TUGAS = '/hrd-detail-surat-tugas';
  static const ABSENSI = '/absensi';
}
